force-app/main/default/objects/Contact/fields/Frequency_Score__c.field-meta.xml
<CustomField>
	<fullName>Frequency_Score__c</fullName>
	<inlineHelpText>Frequency score based on the total number of payments. Used for RFM calculation</inlineHelpText>
	<label>Frequency Score</label>
	<precision>1</precision>
	<scale>0</scale>
	<type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Monetary_Score__c.field-meta.xml
<CustomField>
	<fullName>Monetary_Score__c</fullName>
	<inlineHelpText>Monetary score based on the total amount this contact has paid. Used for RFM calculation</inlineHelpText>
	<label>Monetary Score</label>
	<precision>1</precision>
	<scale>0</scale>
	<type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Recency_Score__c.field-meta.xml
<CustomField>
	<fullName>Recency_Score__c</fullName>
	<inlineHelpText>Recency Score based on the date of last payment. Used for RFM calculation</inlineHelpText>
	<label>Recency Score</label>
	<precision>1</precision>
	<scale>0</scale>
	<type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RFM_Segment__c.field-meta.xml
<CustomField>
	<fullName>RFM_Segment__c</fullName>
	<externalId>true</externalId>
	<inlineHelpText>Recency, Frequency, Monetary based segment of this contact</inlineHelpText>
	<label>RFM Segment</label>
	<length>100</length>
	<type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Grid_Segment__mdt/Engagement_Grid_Segment__mdt.object-meta.xml
<CustomObject>
	<label>Engagement Grid Segment</label>
	<pluralLabel>Engagement Grid Segments</pluralLabel>
</CustomObject>

force-app/main/default/objects/Engagement_Grid_Segment__mdt/fields/Max_RFM_Score__c.field-meta.xml
<CustomField>
	<fullName>Max_RFM_Score__c</fullName>
	<inlineHelpText>Must be in format 1-1-1</inlineHelpText>
	<label>Max RFM Score</label>
	<length>10</length>
	<type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Grid_Segment__mdt/fields/Min_RFM_Score__c.field-meta.xml
<CustomField>
	<fullName>Min_RFM_Score__c</fullName>
	<inlineHelpText>Must be in format 1-1-1</inlineHelpText>
	<label>Min RFM Score</label>
	<length>10</length>
	<required>true</required>
	<type>Text</type>
</CustomField>

force-app/main/default/classes/EngagementGridControllerTest.cls
@isTest
public with sharing class EngagementGridControllerTest {
	@TestSetup
	static void setup() {
		List<Engagement_Grid_Segment__mdt> segments = EngagementGridController.getSegments();
		List<Contact> contacts = new List<Contact>();
		String recordTypeReceivable = [SELECT Id FROM RecordType WHERE Name = 'Receivable' AND sObjectType = 'cpm__Installment__c'][0].Id;
		for (Engagement_Grid_Segment__mdt s : segments) {
			Integer count = Integer.valueof(Math.random() * 20);

			List<String> min = s.Min_RFM_Score__c.split('-');

			for (Integer i = 0; i < count; i++) {
				contacts.add(
					new Contact(
						LastName = s.MasterLabel + i,
						Recency_Score__c = Integer.valueOf(min[0]),
						Frequency_Score__c = Integer.valueOf(min[1]),
						RFM_Segment__c = s.MasterLabel,
						Monetary_Score__c = Integer.valueOf(min[2])
					)
				);
			}
		}
		insert contacts;

		List<cpm__Installment__c> installments = new List<cpm__Installment__c>();

		for (Contact c : contacts) {
			installments.add(new cpm__Installment__c(cpm__Contact__c = c.Id, cpm__Amount__c = 5, cpm__Status__c = 'Collected', RecordTypeId = recordTypeReceivable));
		}

		insert installments;

		List<cpm__Payment__c> payments = new List<cpm__Payment__c>();

		for (cpm__Installment__c i : installments) {
			Date randDate = date.today().addDays((Math.random() * 380).intValue() * -1);
			payments.add(new cpm__Payment__c(cpm__Contact__c = i.cpm__Contact__c, cpm__Amount__c = 5, cpm__Collection_Date__c = randDate, cpm__Installment__c = i.Id));
		}

		insert payments;
	}

	@isTest
	static void getJobProgressTest() {
		test.startTest();
		Id jobId = EngagementGridController.recalculateRFM();

		Map<String, Integer> progress = EngagementGridController.getJobProgress(jobId);

		test.stopTest();

		system.assertEquals(progress.get('total'), [SELECT COUNT() FROM contact]);
	}

	@isTest
	static void getStatsTest() {
		test.startTest();
		Map<String, Object> stats = EngagementGridController.getStats();
		List<Engagement_Grid_Segment__mdt> segments = EngagementGridController.getSegments();
		test.stopTest();

		system.debug(stats);
		for (Engagement_Grid_Segment__mdt s : segments) {
			List<String> min = s.Min_RFM_Score__c.split('-');
			List<String> max = s.Max_RFM_Score__c.split('-');
			system.assertEquals(
				stats.get(s.MasterLabel),
				[
					SELECT COUNT()
					FROM contact
					WHERE
						Recency_Score__c >= :Integer.valueOf(min[0])
						AND Recency_Score__c <= :Integer.valueOf(max[0])
						AND Frequency_Score__c >= :Integer.valueOf(min[1])
						AND Frequency_Score__c <= :Integer.valueOf(max[1])
				]
			);
		}
	}
}